services:
  - type: web
    name: cakebro-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    autoDeploy: true

  - type: web
    name: cakebro-backend
    runtime: docker
    plan: free
    buildCommand: cd backend && docker build -t cakebro-backend .
    startCommand: cd backend && docker run -p $PORT:$PORT cakebro-backend
    autoDeploy: true
